"""
Impact-prioritized diagnostics for data quality defects.

This script consolidates existing single-corruption, anomaly-aware,
compound, propagation, and failure-transferability outputs into a unified
diagnostic index. It does not run new experiments or propose a cleaning
method; it ranks data defects by downstream risk so the results can guide
targeted data-quality intervention.

Outputs:
  results/analysis/diagnostic_priority/single_impact_table.csv
  results/analysis/diagnostic_priority/single_priority_by_family.csv
  results/analysis/diagnostic_priority/anomaly_aware_location_effect.csv
  results/analysis/diagnostic_priority/compound_impact_table.csv
  results/analysis/diagnostic_priority/compound_interaction_summary.csv
  results/analysis/diagnostic_priority/compound_shapley_summary.csv
  results/analysis/diagnostic_priority/diagnostic_priority_index.csv
  results/analysis/diagnostic_priority/*.png
  results/analysis/diagnostic_priority/README.md
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


PROJECT_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_ROOT / "results"
EXPERIMENTS_DIR = RESULTS_DIR / "experiments"
ANALYSIS_DIR = RESULTS_DIR / "analysis"
OUTPUT_DIR = ANALYSIS_DIR / "diagnostic_priority"

MODEL_NAME_MAP = {
    "Autoencoder": "AE",
    "MatrixProfile": "MP",
}

MODEL_ORDER = ["IForest", "LOF", "MP", "AE", "PCA"]


@dataclass(frozen=True)
class SingleExperiment:
    name: str
    relative_path: str
    defect_family: str
    mechanism: str
    condition_fields: tuple[str, ...]
    notes: str


SINGLE_EXPERIMENTS: tuple[SingleExperiment, ...] = (
    SingleExperiment(
        "white_noise_snr",
        "white_noise_snr/summary.csv",
        "white_noise",
        "additive_distribution_shift",
        ("condition", "snr_db"),
        "Controlled additive Gaussian noise at different SNR levels.",
    ),
    SingleExperiment(
        "spikes_normal_only",
        "spikes_normal_only/summary.csv",
        "spikes_normal_region",
        "artificial_anomaly_creation",
        ("fraction", "multiplier"),
        "Spikes injected into normal regions; strong false-positive mechanism.",
    ),
    SingleExperiment(
        "spikes_no_zscore",
        "spikes_no_zscore/summary.csv",
        "spikes",
        "preprocessing_sensitivity",
        ("fraction", "multiplier", "sequential", "sequence_length"),
        "Spikes without z-score normalization; useful ablation.",
    ),
    SingleExperiment(
        "freeze",
        "freeze/summary.csv",
        "sensor_freeze",
        "sensor_persistence",
        ("fraction", "num_stucks", "mean_stuck_length"),
        "Sensor stuck/freeze corruption.",
    ),
    SingleExperiment(
        "freeze_stuck_length",
        "freeze_stuck_length/summary.csv",
        "sensor_freeze",
        "sensor_persistence",
        ("fraction", "stuck_ratio", "mean_stuck_length"),
        "Freeze sensitivity to stuck-run length.",
    ),
    SingleExperiment(
        "gilbert_elliott_true_impact",
        "gilbert_elliott_true_impact/summary.csv",
        "ge_missing",
        "bursty_information_loss",
        ("alpha", "beta", "expected_rate", "expected_burst_len"),
        "Burst missing generated by a Gilbert-Elliott process.",
    ),
    SingleExperiment(
        "gradual_drift",
        "gradual_drift/summary.csv",
        "gradual_drift",
        "distribution_shift",
        ("condition", "drift_type", "severity", "mode"),
        "Gradual/sudden drift and distributional changes.",
    ),
    SingleExperiment(
        "missing_true_impact",
        "missing_true_impact/summary.csv",
        "missing",
        "information_loss",
        ("missing_type", "fraction", "num_bursts", "mean_burst_length"),
        "True impact of point/burst missing values.",
    ),
    SingleExperiment(
        "missing_mnar",
        "missing_mnar/summary.csv",
        "mnar_missing",
        "biased_information_loss",
        ("fraction", "mechanism"),
        "MNAR missingness; missing probability depends on signal properties.",
    ),
    SingleExperiment(
        "missing_mnar_burst",
        "missing_mnar_burst/summary.csv",
        "mnar_burst_missing",
        "bursty_biased_information_loss",
        ("fraction", "num_bursts", "mechanism", "mean_burst_length"),
        "MNAR missingness in bursts.",
    ),
    SingleExperiment(
        "missing_burst_length",
        "missing_burst_length/summary.csv",
        "missing_burst_length",
        "burst_information_loss",
        ("fraction", "burst_ratio", "mean_burst_length", "mean_num_bursts"),
        "Sensitivity to burst length under missing values.",
    ),
    SingleExperiment(
        "missing_masking",
        "missing_masking/summary.csv",
        "missing_masking",
        "masking_sensitivity",
        ("missing_type", "fraction", "num_bursts", "mean_burst_length"),
        "Missing-value masking sensitivity.",
    ),
    SingleExperiment(
        "missing_positional",
        "missing_positional/summary.csv",
        "missing_positional",
        "semantic_location_information_loss",
        ("target", "fraction", "handling"),
        "Position-aware missingness relative to anomaly regions.",
    ),
    SingleExperiment(
        "swap",
        "swap/summary.csv",
        "temporal_swap",
        "temporal_structure_distortion",
        ("condition", "fraction", "max_distance", "swap_length"),
        "General temporal swapping.",
    ),
    SingleExperiment(
        "swap_point",
        "swap_point/summary.csv",
        "point_swap",
        "temporal_structure_distortion",
        ("fraction",),
        "Point-level swap corruption.",
    ),
    SingleExperiment(
        "swap_segment",
        "swap_segment/summary.csv",
        "segment_swap",
        "temporal_structure_distortion",
        ("fraction", "num_swaps", "mean_swap_length"),
        "Segment-level swap corruption.",
    ),
    SingleExperiment(
        "swap_permutation",
        "swap_permutation/summary.csv",
        "temporal_permutation",
        "global_temporal_structure_destruction",
        ("n_segments", "mean_segment_length"),
        "Permutation of time segments; near-random temporal ordering.",
    ),
)


FAMILY_GROUPS: dict[str, str] = {
    "white_noise": "noise",
    "spikes_normal_region": "spikes",
    "spikes": "spikes",
    "sensor_freeze": "freeze",
    "ge_missing": "missing",
    "missing": "missing",
    "mnar_missing": "missing",
    "mnar_burst_missing": "missing",
    "missing_burst_length": "missing",
    "missing_masking": "missing",
    "missing_positional": "missing",
    "gradual_drift": "drift",
    "temporal_swap": "swap",
    "point_swap": "swap",
    "segment_swap": "swap",
    "temporal_permutation": "swap",
}

TRANSFER_EXPERIMENT_MAP: dict[str, str] = {
    "White Noise": "noise",
    "Spikes": "spikes",
    "Missing Data": "missing",
    "Sensor Freeze": "freeze",
    "Segment Swap": "swap",
}


def ensure_output_dir() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def normalize_model_names(series: pd.Series) -> pd.Series:
    return series.replace(MODEL_NAME_MAP)


def load_baseline_means() -> pd.DataFrame:
    path = RESULTS_DIR / "tables" / "baseline_final_subset.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing baseline table: {path}")

    df = pd.read_csv(path)
    if not {"model", "AUC_ROC", "AUC_PR", "VUS_ROC"}.issubset(df.columns):
        raise ValueError(f"Baseline table lacks required metric columns: {path}")

    df["model"] = normalize_model_names(df["model"])
    return (
        df.groupby("model", as_index=False)
        .agg(
            baseline_AUC_ROC=("AUC_ROC", "mean"),
            baseline_AUC_PR=("AUC_PR", "mean"),
            baseline_VUS_ROC=("VUS_ROC", "mean"),
            baseline_n=("file", "nunique"),
        )
        .copy()
    )


def _safe_float(value) -> float:
    try:
        if pd.isna(value):
            return np.nan
        return float(value)
    except Exception:
        return np.nan


def _format_value(value) -> str:
    if pd.isna(value):
        return ""
    if isinstance(value, (int, np.integer)):
        return str(value)
    if isinstance(value, (float, np.floating)):
        if abs(value - round(value)) < 1e-9:
            return str(int(round(value)))
        return f"{value:.4g}"
    return str(value)


def make_condition_label(row: pd.Series, fields: Iterable[str]) -> str:
    parts: list[str] = []
    for field in fields:
        if field in row.index and not pd.isna(row[field]) and str(row[field]) != "":
            parts.append(f"{field}={_format_value(row[field])}")
    if parts:
        return ", ".join(parts)
    if "condition" in row.index and not pd.isna(row["condition"]):
        return str(row["condition"])
    return "condition"


def compute_observed_severity(df: pd.DataFrame, exp: SingleExperiment) -> pd.Series:
    """Create a 0-1 severity proxy from each experiment's condition columns."""
    idx = df.index
    candidates: list[pd.Series] = []

    if "snr_db" in df.columns and df["snr_db"].notna().any():
        snr = pd.to_numeric(df["snr_db"], errors="coerce")
        # Lower SNR means more severe noise.
        denom = max(float(snr.max() - snr.min()), 1e-12)
        candidates.append((snr.max() - snr) / denom)

    if "fraction" in df.columns and df["fraction"].notna().any():
        frac = pd.to_numeric(df["fraction"], errors="coerce")
        max_frac = max(float(frac.max()), 1e-12)
        candidates.append(frac / max_frac)

    if "multiplier" in df.columns and df["multiplier"].notna().any():
        mult = pd.to_numeric(df["multiplier"], errors="coerce")
        max_mult = max(float(mult.max()), 1e-12)
        candidates.append(mult / max_mult)

    if "num_bursts" in df.columns and df["num_bursts"].notna().any():
        bursts = pd.to_numeric(df["num_bursts"], errors="coerce")
        max_bursts = max(float(bursts.max()), 1e-12)
        candidates.append(bursts / max_bursts)

    if "n_segments" in df.columns and df["n_segments"].notna().any():
        segments = pd.to_numeric(df["n_segments"], errors="coerce")
        max_segments = max(float(segments.max()), 1e-12)
        candidates.append(segments / max_segments)

    if "severity" in df.columns and df["severity"].notna().any():
        severity_map = {"low": 0.33, "med": 0.66, "medium": 0.66, "high": 1.0, "severe": 1.0}
        sev = df["severity"].astype(str).str.lower().map(severity_map)
        if sev.notna().any():
            candidates.append(sev)

    if not candidates:
        return pd.Series(np.nan, index=idx)

    stacked = pd.concat(candidates, axis=1)
    return stacked.mean(axis=1, skipna=True).clip(0.0, 1.0)


def load_single_impact_table(baseline: pd.DataFrame) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []

    for exp in SINGLE_EXPERIMENTS:
        path = EXPERIMENTS_DIR / exp.relative_path
        if not path.exists():
            print(f"[WARN] Missing single summary: {path}")
            continue

        df = pd.read_csv(path)
        if "mean_AUC_ROC" not in df.columns or "model" not in df.columns:
            print(f"[WARN] Skipping {exp.name}: missing mean_AUC_ROC/model")
            continue

        df = df.copy()
        df["model"] = normalize_model_names(df["model"])
        df = df.merge(baseline, on="model", how="left")
        df = df[df["baseline_AUC_ROC"].notna()].copy()

        if df.empty:
            print(f"[WARN] Skipping {exp.name}: no matching model baselines")
            continue

        out = pd.DataFrame(
            {
                "experiment": exp.name,
                "defect_family": exp.defect_family,
                "family_group": FAMILY_GROUPS.get(exp.defect_family, exp.defect_family),
                "mechanism": exp.mechanism,
                "model": df["model"],
                "condition": df.apply(lambda r: make_condition_label(r, exp.condition_fields), axis=1),
                "n_runs": pd.to_numeric(df.get("n_runs", df.get("n", np.nan)), errors="coerce"),
                "baseline_AUC_ROC": df["baseline_AUC_ROC"],
                "mean_AUC_ROC": pd.to_numeric(df["mean_AUC_ROC"], errors="coerce"),
                "mean_AUC_PR": pd.to_numeric(df.get("mean_AUC_PR", np.nan), errors="coerce"),
                "mean_VUS_ROC": pd.to_numeric(df.get("mean_VUS_ROC", np.nan), errors="coerce"),
                "severity_proxy": compute_observed_severity(df, exp),
                "notes": exp.notes,
            }
        )
        out["auc_drop"] = out["baseline_AUC_ROC"] - out["mean_AUC_ROC"]
        out["positive_auc_drop"] = out["auc_drop"].clip(lower=0.0)
        out["auc_drop_pct"] = np.where(
            out["baseline_AUC_ROC"].abs() > 1e-12,
            100.0 * out["auc_drop"] / out["baseline_AUC_ROC"],
            np.nan,
        )
        frames.append(out)
        print(f"[INFO] Loaded single summary {exp.name}: {len(out)} rows")

    if not frames:
        return pd.DataFrame()

    table = pd.concat(frames, ignore_index=True)
    table = table.sort_values(["positive_auc_drop", "experiment"], ascending=[False, True])
    return table


def load_anomaly_aware_location_effect(baseline: pd.DataFrame) -> pd.DataFrame:
    path = EXPERIMENTS_DIR / "anomaly_aware_corruption" / "summary.csv"
    if not path.exists():
        print(f"[WARN] Missing anomaly-aware summary: {path}")
        return pd.DataFrame()

    df = pd.read_csv(path)
    df["model"] = normalize_model_names(df["model"])
    df = df.merge(baseline, on="model", how="left")
    df["auc_drop"] = df["baseline_AUC_ROC"] - df["mean_AUC_ROC"]
    df["positive_auc_drop"] = df["auc_drop"].clip(lower=0.0)

    grouped = (
        df.groupby(["corruption_type", "target_mode", "model"], as_index=False)
        .agg(
            mean_AUC_ROC=("mean_AUC_ROC", "mean"),
            mean_AUC_PR=("mean_AUC_PR", "mean"),
            mean_VUS_ROC=("mean_VUS_ROC", "mean"),
            mean_positive_auc_drop=("positive_auc_drop", "mean"),
            mean_corrupted_normal_points=("mean_corrupted_normal_points", "mean"),
            mean_corrupted_anomaly_points=("mean_corrupted_anomaly_points", "mean"),
        )
        .copy()
    )

    pivot = grouped.pivot_table(
        index=["corruption_type", "model"],
        columns="target_mode",
        values="mean_AUC_ROC",
        aggfunc="mean",
    ).reset_index()
    for col in ["only_normal", "only_anomaly", "mixed"]:
        if col not in pivot.columns:
            pivot[col] = np.nan

    pivot["location_gap_abs"] = (pivot["only_anomaly"] - pivot["only_normal"]).abs()
    pivot["anomaly_minus_normal_auc"] = pivot["only_anomaly"] - pivot["only_normal"]
    pivot["mechanism_reading"] = np.where(
        pivot["anomaly_minus_normal_auc"] < 0,
        "anomaly masking / false negatives",
        "signal amplification vs normal false positives",
    )

    return grouped.merge(
        pivot[
            [
                "corruption_type",
                "model",
                "only_normal",
                "only_anomaly",
                "mixed",
                "location_gap_abs",
                "anomaly_minus_normal_auc",
                "mechanism_reading",
            ]
        ],
        on=["corruption_type", "model"],
        how="left",
    )


def load_compound_tables(baseline: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    summary_path = EXPERIMENTS_DIR / "compound_corruptions" / "summary.csv"
    if summary_path.exists():
        df = pd.read_csv(summary_path)
        df["model"] = normalize_model_names(df["model"])
        df = df.merge(baseline, on="model", how="left")
        df["auc_drop"] = df["baseline_AUC_ROC"] - pd.to_numeric(df["mean_AUC_ROC"], errors="coerce")
        df["positive_auc_drop"] = df["auc_drop"].clip(lower=0.0)
        compound = df[df["condition_type"].astype(str).eq("compound")].copy()
        compound = compound.sort_values("positive_auc_drop", ascending=False)
    else:
        print(f"[WARN] Missing compound summary: {summary_path}")
        compound = pd.DataFrame()

    interaction_path = EXPERIMENTS_DIR / "compound_corruptions" / "interaction_summary.csv"
    if interaction_path.exists():
        interaction = pd.read_csv(interaction_path)
        interaction["model"] = normalize_model_names(interaction["model"])
    else:
        print(f"[WARN] Missing interaction summary: {interaction_path}")
        interaction = pd.DataFrame()

    shapley_path = EXPERIMENTS_DIR / "compound_corruptions" / "shapley_summary.csv"
    if shapley_path.exists():
        shapley = pd.read_csv(shapley_path)
        shapley["model"] = normalize_model_names(shapley["model"])
        shapley["family_group"] = shapley["corruption"].map(
            {"noise": "noise", "spikes": "spikes", "missing": "missing"}
        )
    else:
        print(f"[WARN] Missing Shapley summary: {shapley_path}")
        shapley = pd.DataFrame()

    return compound, interaction, shapley


def load_propagation_scope() -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    path = EXPERIMENTS_DIR / "propagation" / "propagation_summary.csv"
    if path.exists():
        df = pd.read_csv(path)
        df["source"] = "propagation"
        frames.append(df)

    path_multi = EXPERIMENTS_DIR / "propagation_multiscale" / "propagation_summary.csv"
    if path_multi.exists():
        df = pd.read_csv(path_multi)
        # Keep all scales; aggregation below absorbs the scale dimension.
        df["source"] = "propagation_multiscale"
        frames.append(df)

    if not frames:
        return pd.DataFrame()

    df = pd.concat(frames, ignore_index=True)
    df["model"] = normalize_model_names(df["model"])
    df["family_group"] = df["corruption_type"].map(
        {"noise": "noise", "spikes": "spikes", "missing": "missing", "freeze": "freeze"}
    )
    df = df[df["family_group"].notna()].copy()
    agg = (
        df.groupby("family_group", as_index=False)
        .agg(
            propagation_ratio=("mean_ratio", "mean"),
            propagation_ratio_max=("mean_ratio", "max"),
            far_zone_diff=("mean_diff_far", "mean"),
            far_zone_diff_max=("mean_diff_far", "max"),
        )
        .copy()
    )
    return agg


def load_transferability() -> pd.DataFrame:
    path = ANALYSIS_DIR / "failure_transferability_v2" / "per_pair_summary.csv"
    if not path.exists():
        print(f"[WARN] Missing transferability table: {path}")
        return pd.DataFrame()

    df = pd.read_csv(path)
    df["family_group"] = df["experiment"].map(TRANSFER_EXPERIMENT_MAP)
    df = df[df["family_group"].notna()].copy()
    return (
        df.groupby("family_group", as_index=False)
        .agg(
            transferability_jaccard=("jaccard", "mean"),
            transferability_jaccard_max=("jaccard", "max"),
            transferability_pairs=("jaccard", "count"),
        )
        .copy()
    )


def _minmax(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce")
    if values.notna().sum() == 0:
        return pd.Series(np.nan, index=series.index)
    min_v = float(values.min())
    max_v = float(values.max())
    if max_v - min_v < 1e-12:
        return pd.Series(1.0, index=series.index)
    return ((values - min_v) / (max_v - min_v)).clip(0.0, 1.0)


def build_single_priority(single_table: pd.DataFrame) -> pd.DataFrame:
    if single_table.empty:
        return pd.DataFrame()

    priority = (
        single_table.groupby(["defect_family", "family_group", "mechanism"], as_index=False)
        .agg(
            n_conditions=("condition", "count"),
            n_models=("model", "nunique"),
            mean_positive_auc_drop=("positive_auc_drop", "mean"),
            median_positive_auc_drop=("positive_auc_drop", "median"),
            max_positive_auc_drop=("positive_auc_drop", "max"),
            min_mean_AUC_ROC=("mean_AUC_ROC", "min"),
            mean_AUC_ROC=("mean_AUC_ROC", "mean"),
            mean_auc_drop_pct=("auc_drop_pct", "mean"),
            mean_severity_proxy=("severity_proxy", "mean"),
        )
        .copy()
    )
    priority["impact_score"] = _minmax(priority["mean_positive_auc_drop"])
    priority["worst_case_score"] = _minmax(priority["max_positive_auc_drop"])
    priority["single_priority_score"] = (
        0.65 * priority["impact_score"] + 0.35 * priority["worst_case_score"]
    )
    return priority.sort_values("single_priority_score", ascending=False)


def build_diagnostic_priority_index(
    single_priority: pd.DataFrame,
    location_effect: pd.DataFrame,
    shapley: pd.DataFrame,
    propagation: pd.DataFrame,
    transferability: pd.DataFrame,
) -> pd.DataFrame:
    if single_priority.empty:
        return pd.DataFrame()

    index = single_priority.copy()

    if not location_effect.empty:
        loc = (
            location_effect.groupby("corruption_type", as_index=False)
            .agg(location_gap_abs=("location_gap_abs", "mean"))
            .copy()
        )
        loc["family_group"] = loc["corruption_type"].map(
            {"noise": "noise", "spikes": "spikes", "missing": "missing"}
        )
        loc = loc.groupby("family_group", as_index=False).agg(
            location_sensitivity=("location_gap_abs", "mean")
        )
        loc["location_score"] = _minmax(loc["location_sensitivity"])
        index = index.merge(loc[["family_group", "location_sensitivity", "location_score"]], on="family_group", how="left")
    else:
        index["location_sensitivity"] = np.nan
        index["location_score"] = np.nan

    if not shapley.empty:
        shp = (
            shapley.groupby("family_group", as_index=False)
            .agg(
                compound_shapley_pct=("mean_pct", "mean"),
                compound_shapley_value=("mean_shapley", "mean"),
            )
            .copy()
        )
        shp["compound_score"] = _minmax(shp["compound_shapley_pct"])
        index = index.merge(shp, on="family_group", how="left")
    else:
        index["compound_shapley_pct"] = np.nan
        index["compound_shapley_value"] = np.nan
        index["compound_score"] = np.nan

    if not propagation.empty:
        prop = propagation.copy()
        prop["propagation_score"] = _minmax(prop["far_zone_diff"])
        index = index.merge(
            prop[
                [
                    "family_group",
                    "propagation_ratio",
                    "propagation_ratio_max",
                    "far_zone_diff",
                    "far_zone_diff_max",
                    "propagation_score",
                ]
            ],
            on="family_group",
            how="left",
        )
    else:
        index["propagation_score"] = np.nan

    if not transferability.empty:
        trans = transferability.copy()
        trans["transferability_score"] = _minmax(trans["transferability_jaccard"])
        index = index.merge(trans, on="family_group", how="left")
    else:
        index["transferability_score"] = np.nan

    component_weights = {
        "single_priority_score": 0.35,
        "location_score": 0.20,
        "compound_score": 0.20,
        "propagation_score": 0.15,
        "transferability_score": 0.10,
    }

    fixed_score = pd.Series(0.0, index=index.index)
    available_score = pd.Series(0.0, index=index.index)
    available_weight = pd.Series(0.0, index=index.index)
    evidence_axes = pd.Series(0, index=index.index)

    for col, weight in component_weights.items():
        if col not in index.columns:
            index[col] = np.nan
        values = pd.to_numeric(index[col], errors="coerce")
        fixed_score += values.fillna(0.0) * weight
        mask = values.notna()
        available_score += values.fillna(0.0) * weight
        available_weight += mask.astype(float) * weight
        evidence_axes += mask.astype(int)

    index["dpi_score"] = fixed_score
    index["dpi_available_weighted_score"] = np.where(available_weight > 0, available_score / available_weight, np.nan)
    index["evidence_axes"] = evidence_axes
    index["priority_rank"] = index["dpi_score"].rank(ascending=False, method="dense").astype("Int64")

    return index.sort_values(["dpi_score", "evidence_axes"], ascending=[False, False])


def save_csv(df: pd.DataFrame, filename: str) -> None:
    path = OUTPUT_DIR / filename
    df.to_csv(path, index=False)
    print(f"[OK] {path} ({len(df)} rows)")


def _ordered_models(columns: Iterable[str]) -> list[str]:
    cols = list(columns)
    ordered = [m for m in MODEL_ORDER if m in cols]
    ordered.extend([m for m in cols if m not in ordered])
    return ordered


def plot_single_impact_heatmap(single_table: pd.DataFrame) -> None:
    if single_table.empty:
        return
    pivot = single_table.pivot_table(
        index="defect_family",
        columns="model",
        values="positive_auc_drop",
        aggfunc="mean",
    )
    if pivot.empty:
        return
    pivot = pivot[_ordered_models(pivot.columns)]
    pivot = pivot.loc[pivot.mean(axis=1).sort_values(ascending=True).index]

    fig_h = max(6, 0.35 * len(pivot) + 2)
    fig, ax = plt.subplots(figsize=(9, fig_h))
    image = ax.imshow(pivot.values, aspect="auto", cmap="Reds")
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index)
    ax.set_title("Mean Positive AUC Drop by Single Defect and Model")
    ax.set_xlabel("Model")
    ax.set_ylabel("Single defect family")
    fig.colorbar(image, ax=ax, label="Positive AUC drop")

    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            value = pivot.iloc[i, j]
            if pd.notna(value):
                ax.text(j, i, f"{value:.2f}", ha="center", va="center", fontsize=8)

    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "single_impact_heatmap.png", dpi=220)
    plt.close(fig)


def plot_priority_bar(priority_index: pd.DataFrame) -> None:
    if priority_index.empty:
        return
    top = priority_index.sort_values("dpi_score", ascending=True).tail(15)
    fig, ax = plt.subplots(figsize=(9, max(5, 0.38 * len(top) + 1.5)))
    ax.barh(top["defect_family"], top["dpi_score"], color="#356859")
    ax.set_xlabel("Diagnostic Priority Index")
    ax.set_title("Impact-Prioritized Data Quality Risk Ranking")
    for y, value in enumerate(top["dpi_score"]):
        ax.text(value + 0.01, y, f"{value:.2f}", va="center", fontsize=8)
    ax.set_xlim(0, min(1.1, max(1.0, float(top["dpi_score"].max()) + 0.12)))
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "diagnostic_priority_ranking.png", dpi=220)
    plt.close(fig)


def plot_location_effect(location_effect: pd.DataFrame) -> None:
    if location_effect.empty:
        return
    pivot = (
        location_effect.groupby(["corruption_type", "model"], as_index=False)
        .agg(gap=("location_gap_abs", "mean"))
        .pivot(index="corruption_type", columns="model", values="gap")
    )
    if pivot.empty:
        return
    pivot = pivot[_ordered_models(pivot.columns)]
    fig, ax = plt.subplots(figsize=(8, 4))
    x = np.arange(len(pivot.index))
    width = 0.8 / max(len(pivot.columns), 1)
    for offset, model in enumerate(pivot.columns):
        ax.bar(x + offset * width, pivot[model], width=width, label=model)
    ax.set_xticks(x + width * (len(pivot.columns) - 1) / 2)
    ax.set_xticklabels(pivot.index)
    ax.set_ylabel("|AUC(only anomaly) - AUC(only normal)|")
    ax.set_title("Anomaly-Aware Location Sensitivity")
    ax.legend(frameon=False, ncol=2)
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "anomaly_aware_location_gap.png", dpi=220)
    plt.close(fig)


def plot_compound_shapley(shapley: pd.DataFrame) -> None:
    if shapley.empty:
        return
    data = shapley.sort_values("mean_pct", ascending=True)
    fig, ax = plt.subplots(figsize=(6, 3.6))
    ax.barh(data["corruption"], data["mean_pct"], color="#a44a3f")
    ax.set_xlabel("Mean Shapley Contribution (%)")
    ax.set_title("Compound Attribution: noise + spikes + missing")
    for y, value in enumerate(data["mean_pct"]):
        ax.text(value + 1, y, f"{value:.1f}%", va="center", fontsize=9)
    ax.set_xlim(0, max(60, float(data["mean_pct"].max()) + 10))
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "compound_shapley_contributions.png", dpi=220)
    plt.close(fig)


def dataframe_to_markdown(df: pd.DataFrame, floatfmt: str = ".4f") -> str:
    """Render a small DataFrame as Markdown without the optional tabulate dependency."""
    if df.empty:
        return "_No rows available._"

    def fmt(value) -> str:
        if pd.isna(value):
            return ""
        if isinstance(value, (float, np.floating)):
            return format(float(value), floatfmt)
        return str(value)

    columns = [str(c) for c in df.columns]
    rows = [[fmt(value) for value in row] for row in df.to_numpy()]
    widths = []
    for i, col in enumerate(columns):
        values = [row[i] for row in rows]
        widths.append(max(len(col), *(len(v) for v in values)))

    def render_row(values: list[str]) -> str:
        padded = [values[i].ljust(widths[i]) for i in range(len(values))]
        return "| " + " | ".join(padded) + " |"

    header = render_row(columns)
    separator = "| " + " | ".join("-" * w for w in widths) + " |"
    body = [render_row(row) for row in rows]
    return "\n".join([header, separator, *body])


def write_readme(
    single_priority: pd.DataFrame,
    priority_index: pd.DataFrame,
    location_effect: pd.DataFrame,
    shapley: pd.DataFrame,
) -> None:
    top_single = single_priority.head(8)[
        ["defect_family", "mechanism", "mean_positive_auc_drop", "max_positive_auc_drop"]
    ]
    top_dpi = priority_index.head(8)[
        ["priority_rank", "defect_family", "mechanism", "dpi_score", "evidence_axes"]
    ]

    if not location_effect.empty:
        loc_summary = (
            location_effect.groupby("corruption_type", as_index=False)
            .agg(location_gap_abs=("location_gap_abs", "mean"))
            .sort_values("location_gap_abs", ascending=False)
        )
    else:
        loc_summary = pd.DataFrame()

    lines = [
        "# Diagnostic Priority Analysis",
        "",
        "This folder is generated by `python src/analysis/diagnostic_priority.py`.",
        "It consolidates existing experiment outputs; it does not run new corruption or cleaning experiments.",
        "",
        "## Main Tables",
        "",
        "- `single_impact_table.csv`: row-level summary of all configured single-corruption conditions.",
        "- `single_priority_by_family.csv`: aggregated priority ranking from single-corruption impact.",
        "- `anomaly_aware_location_effect.csv`: normal-vs-anomaly location effect from anomaly-aware corruption.",
        "- `compound_impact_table.csv`: compound conditions with AUC drops versus clean baselines.",
        "- `compound_interaction_summary.csv`: additive/synergistic/sub-additive interaction summary.",
        "- `compound_shapley_summary.csv`: Shapley attribution for compound corruption.",
        "- `diagnostic_priority_index.csv`: unified diagnostic priority index.",
        "",
        "## Top Single Defects by Observed Impact",
        "",
        dataframe_to_markdown(top_single) if not top_single.empty else "_No single table available._",
        "",
        "## Top Diagnostic Priorities",
        "",
        dataframe_to_markdown(top_dpi) if not top_dpi.empty else "_No priority index available._",
        "",
        "## Location Sensitivity",
        "",
        dataframe_to_markdown(loc_summary) if not loc_summary.empty else "_No anomaly-aware table available._",
        "",
        "## Compound Shapley Summary",
        "",
        dataframe_to_markdown(shapley) if not shapley.empty else "_No Shapley table available._",
        "",
        "## Interpretation",
        "",
        "Use this analysis as a diagnostic framework: high-priority rows identify data defects that deserve targeted data-quality attention because they produce large downstream anomaly-detection degradation, strong location dependence, compound dominance, broad propagation, or cross-model transferability.",
    ]
    path = OUTPUT_DIR / "README.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] {path}")


def main() -> None:
    ensure_output_dir()
    baseline = load_baseline_means()

    single_table = load_single_impact_table(baseline)
    save_csv(single_table, "single_impact_table.csv")

    single_priority = build_single_priority(single_table)
    save_csv(single_priority, "single_priority_by_family.csv")

    location_effect = load_anomaly_aware_location_effect(baseline)
    save_csv(location_effect, "anomaly_aware_location_effect.csv")

    compound, interaction, shapley = load_compound_tables(baseline)
    save_csv(compound, "compound_impact_table.csv")
    save_csv(interaction, "compound_interaction_summary.csv")
    save_csv(shapley, "compound_shapley_summary.csv")

    propagation = load_propagation_scope()
    save_csv(propagation, "propagation_scope_by_family.csv")

    transferability = load_transferability()
    save_csv(transferability, "failure_transferability_by_family.csv")

    priority_index = build_diagnostic_priority_index(
        single_priority=single_priority,
        location_effect=location_effect,
        shapley=shapley,
        propagation=propagation,
        transferability=transferability,
    )
    save_csv(priority_index, "diagnostic_priority_index.csv")

    plot_single_impact_heatmap(single_table)
    plot_priority_bar(priority_index)
    plot_location_effect(location_effect)
    plot_compound_shapley(shapley)
    write_readme(single_priority, priority_index, location_effect, shapley)

    print("\nTop diagnostic priorities:")
    if not priority_index.empty:
        print(
            priority_index[
                [
                    "priority_rank",
                    "defect_family",
                    "mechanism",
                    "dpi_score",
                    "single_priority_score",
                    "location_score",
                    "compound_score",
                    "propagation_score",
                    "transferability_score",
                    "evidence_axes",
                ]
            ]
            .head(12)
            .to_string(index=False)
        )


if __name__ == "__main__":
    main()
